### ISSUE TITLE
requirements缺少组件

### ISSUE THREAD

**Issue by Morphiism** [XJF2332/GOT-OCR-2-GUI#13]
**个人环境**：python 3.11.9 + torch 2.4.1 + cu124

**问题描述**： 

在安装 torch 和 requirements 后运行 GUI.py 出现错误：

```powershell
ModuleNotFoundError: No module named 'frontend'
```

**解决方法**：

执行

```powershell
pip install frontend
pip install tools
```

并在安装目录中新建一个static文件夹，文件结构如下：

```
GOT-OCR-2-GUI
└─static
```

之后可以运行

```powershell
python GUI.py
```

**Comment by KirariSpark** [comment]
![Image_1729729205851](https://github.com/user-attachments/assets/7de87e2e-106f-4cef-ab83-cd6eae0d7af9)
能不能提供更多信息？因为我的环境里也是没有frontend和tools的，但没发现问题，我也不知道为什么会出现这个问题。如果能提供更多信息的话我可以更快定位问题。

**Comment by KirariSpark** [comment]
比如说是什么模块import失败了才报错的之类（一定是别的模块import的frontend和tools，因为我自己没有import这些东西😰😰😰）

**Comment by Morphiism** [comment]
直接运行就出现

```python
Traceback (most recent call last):
  File "D:\AI\GOT-OCR-2-GUI\GUI.py", line 25, in <module>
    import scripts.PDF2ImagePlusRenderer as PDFHandler
  File "D:\AI\GOT-OCR-2-GUI\scripts\PDF2ImagePlusRenderer.py", line 1, in <module>
    import fitz
  File "D:\ProgramData\anaconda3\envs\gotgui\Lib\site-packages\fitz\__init__.py", line 1, in <module>
    from frontend import *
ModuleNotFoundError: No module named 'frontend'
```

安装 frontend 后出现

```python
Traceback (most recent call last):
  File "D:\AI\GOT-OCR-2-GUI\GUI.py", line 25, in <module>
    import scripts.PDF2ImagePlusRenderer as PDFHandler
  File "D:\AI\GOT-OCR-2-GUI\scripts\PDF2ImagePlusRenderer.py", line 1, in <module>
    import fitz
  File "D:\ProgramData\anaconda3\envs\gotgui\Lib\site-packages\fitz\__init__.py", line 1, in <module>
    from frontend import *
  File "C:\Users\gky\AppData\Roaming\Python\Python311\site-packages\frontend\__init__.py", line 1, in <module>
    from .events import *
  File "C:\Users\gky\AppData\Roaming\Python\Python311\site-packages\frontend\events\__init__.py", line 1, in <module>
    from .clipboard import *
  File "C:\Users\gky\AppData\Roaming\Python\Python311\site-packages\frontend\events\clipboard.py", line 2, in <module>
    from ..dom import Event
  File "C:\Users\gky\AppData\Roaming\Python\Python311\site-packages\frontend\dom.py", line 439, in <module>
    from . import dispatcher
  File "C:\Users\gky\AppData\Roaming\Python\Python311\site-packages\frontend\dispatcher.py", line 15, in <module>
    from . import config, server
  File "C:\Users\gky\AppData\Roaming\Python\Python311\site-packages\frontend\server.py", line 24, in <module>
    app.mount(config.STATIC_ROUTE, StaticFiles(directory=config.STATIC_DIRECTORY), name=config.STATIC_NAME)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\anaconda3\envs\gotgui\Lib\site-packages\starlette\staticfiles.py", line 56, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'static/' does not exist
```

所以我新建了一个static文件夹

然后又出现

```python
Traceback (most recent call last):
  File "D:\AI\GOT-OCR-2-GUI\GUI.py", line 25, in <module>
    import scripts.PDF2ImagePlusRenderer as PDFHandler
  File "D:\AI\GOT-OCR-2-GUI\scripts\PDF2ImagePlusRenderer.py", line 1, in <module>
    import fitz
  File "D:\ProgramData\anaconda3\envs\gotgui\Lib\site-packages\fitz\__init__.py", line 2, in <module>
    import tools
ModuleNotFoundError: No module named 'tools'
```

安装 tools 以后就可以正常运行了

**Comment by KirariSpark** [comment]
感谢，已经找到问题了，看起来是fitz的问题
就很神奇，你如果把这玩意放进requirements.txt它就会出这样的问题，如果你单独拿出来安装就不会
我试了一下，只要先pip uninstall在pip install fitz和pymupdf这两个玩意就好了，安装的顺序还有要求，pip install -U也不行，不然还会报新的错误，巨诡异

**Comment by KirariSpark** [comment]
我在alpha分支的update requirements and readmes更新了依赖和readme，应该没问题了，过一段时间合并到main

**Comment by Morphiism** [comment]
重新部署以后可以正常运行了
